import { Network } from "bitcoinjs-lib";
import { ContractLoader } from "../contract/contract-loader";
import { AddressBalanceDao } from "../dao/address-balance-dao";
import { AssetDao } from "../dao/asset-dao";
import { AssetSupplyDao } from "../dao/asset-supply-dao";
import { OpCommitDao } from "../dao/commit-dao";
import { CommunityDao } from "../dao/community-dao";
import { DepositDao } from "../dao/deposit-dao";
import { OpEventDao } from "../dao/event-dao";
import { FeeRateDao } from "../dao/feerate-dao";
import { LockUserDao } from "../dao/lock-user-dao";
import { LpRewardHistoryDao } from "../dao/lp-reward-history-dao";
import { LpRewardPoolDao } from "../dao/lp-reward-pool-dao";
import { LpRewardUserDao } from "../dao/lp-reward-user-dao";
import { MatchingDao } from "../dao/matching-dao";
import { OpsStatsDao } from "../dao/ops-stats-dao";
import { PayDao } from "../dao/pay-dao";
import { PoolListDao } from "../dao/pool-list-dao";
import { RecordApproveDao } from "../dao/record-approve-dao";
import { RecordGasDao } from "../dao/record-gas-dao";
import { RecordLiqDao } from "../dao/record-liq-dao";
import { RecordLockLpDao } from "../dao/record-lock-lp-dao";
import { RecordMultiSwapDao } from "../dao/record-multi-swap-dao";
import { RecordSendDao } from "../dao/record-send-dao";
import { RecordSwapDao } from "../dao/record-swap-dao";
import { RecordUnlockLpDao } from "../dao/record-unlock-lp-dao";
import { RewardCurveDao } from "../dao/reward-curve-dao";
import { SequencerTxDao } from "../dao/sequencer-tx-dao";
import { SequencerUtxoDao } from "../dao/sequencer-utxo-dao";
import { SnapshotAssetDao } from "../dao/snapshot-asset-dao";
import { SnapshotKLastDao } from "../dao/snapshot-klast-dao";
import { SnapshotSupplyDao } from "../dao/snapshot-supply-dao";
import { StakeEpochDao } from "../dao/stake-epoch-dao";
import { StakeHistoryDao } from "../dao/stake-history-dao";
import { StakePoolDao } from "../dao/stake-pool-dao";
import { StakeUserDao } from "../dao/stake-user-dao";
import { StatusDao } from "../dao/status-dao";
import { TaskDao } from "../dao/task-dao";
import { TaskMetaDao } from "../dao/task-meta-dao";
import { TickDao } from "../dao/tick-dao";
import { WithdrawDao } from "../dao/withdraw-dao";
import { AddressBalanceWorker } from "../domain/address-balance-worker";
import { API } from "../domain/api";
import { Builder } from "../domain/builder";
import { ConditionalWithdraw } from "../domain/conditional-withdraw";
import { Decimal } from "../domain/decimal";
import { Deposit } from "../domain/deposit";
import { Env } from "../domain/env";
import { Keyring } from "../domain/keyring";
import { LockLp } from "../domain/lock-lp";
import { Matching } from "../domain/matching";
import { Metric } from "../domain/metric";
import { MultiRoutes } from "../domain/multi-routes";
import { Operator } from "../domain/operator";
import { OpsStats } from "../domain/ops-stats";
import { Query } from "../domain/query";
import { RewardCurve } from "../domain/reward-curve";
import { Sender } from "../domain/sender";
import { Stake } from "../domain/stake";
import { StakePoolMgr } from "../domain/stake-pool-mgr";
import { Statistic } from "../domain/statistic";
import { TaskList } from "../domain/task-list";
import { DirectWithdraw } from "../domain/withdraw";
import { SimpleBridgeApi } from "../lib/bridge-api";
import { OpenApi } from "../lib/open-api";
import { DateLogger } from "../utils/logger";
import { MongoUtils } from "../utils/mongo-utils";
import { Config } from "./domain";

declare global {
  var fatal: boolean;
  var inited: boolean;
  var isFractal: boolean;
  var isTestnet: boolean;
  var network: Network;
  var config: Config;
  var mongoUtils: MongoUtils;
  var sender: Sender;
  var builder: Builder;
  var operator: Operator;
  var api: API;
  var simpleBridgeAPI: SimpleBridgeApi;
  var openAPI: OpenApi;
  var decimal: Decimal;
  var query: Query;
  var env: Env;
  var logger: DateLogger;
  var contractLoader: ContractLoader;
  var deposit: Deposit;
  var conditionalWithdraw: ConditionalWithdraw;
  var directWithdraw: DirectWithdraw;
  var matching: Matching;
  var keyring: Keyring;
  var metric: Metric;
  var statistic: Statistic;
  var stakePoolMgr: StakePoolMgr;
  var stake: Stake;
  var opsStats: OpsStats;
  var rewardCurve: RewardCurve;
  var taskList: TaskList;
  var lockLp: LockLp;
  var multiRoutes: MultiRoutes;

  var opCommitDao: OpCommitDao;
  var opEventDao: OpEventDao;
  var tickDao: TickDao;
  var addressBalanceDao: AddressBalanceDao;
  var addressBalanceWorker: AddressBalanceWorker;
  var recordLiqDao: RecordLiqDao;
  var recordSwapDao: RecordSwapDao;
  var recordApproveDao: RecordApproveDao;
  var recordSendDao: RecordSendDao;
  var sequencerUtxoDao: SequencerUtxoDao;
  var sequencerTxDao: SequencerTxDao;
  var withdrawDao: WithdrawDao;
  var matchingDao: MatchingDao;
  var depositDao: DepositDao;
  var recordGasDao: RecordGasDao;
  var feeRateDao: FeeRateDao;
  var statusDao: StatusDao;
  var snapshotAssetDao: SnapshotAssetDao;
  var snapshotKLastDao: SnapshotKLastDao;
  var snapshotSupplyDao: SnapshotSupplyDao;
  var assetDao: AssetDao;
  var assetSupplyDao: AssetSupplyDao;
  var poolListDao: PoolListDao;
  var stakeEpochDao: StakeEpochDao;
  var stakePoolDao: StakePoolDao;
  var stakeUserDao: StakeUserDao;
  var stakeHistoryDao: StakeHistoryDao;
  var payDao: PayDao;
  var snapshotLpRewardPoolDao: LpRewardPoolDao;
  var snapshotLpRewardUserDao: LpRewardUserDao;
  var lpRewardHistoryDao: LpRewardHistoryDao;
  var taskDao: TaskDao;
  var taskMetaDao: TaskMetaDao;
  var opsStatsDao: OpsStatsDao;
  var communityDao: CommunityDao;
  var rewardCurveDao: RewardCurveDao;
  var recordLockLpDao: RecordLockLpDao;
  var lockUserDao: LockUserDao;
  var recordUnlockLpDao: RecordUnlockLpDao;
  var recordMultiSwapDao: RecordMultiSwapDao;
}

export {};
